services:
  app:
    build:
      dockerfile: ./docker-build/app/Dockerfile
      context: ./
    environment:
      APP_CONFIG__DB__URL: postgresql+asyncpg://user:password@pg:5432/polystats
      APP_CONFIG__DB__ECHO: 0
    ports:
      - "8000:8000"
    depends_on:
      pg:
        condition: service_healthy
#    command:
#      - python
#      - run_main.py
    develop:
      watch:
        - action: sync+restart
          path: ./fastapi-application
          target: /app
        - action: rebuild
          path: ./poetry.lock

  pg:
    image: postgres:16.4
    environment:
      POSTGRES_DB: polystats
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
#    ports:
#      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d polystats" ]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  pgdata: