services:
  test-runner:
    build:
      context: .
      dockerfile: docker-build/app/Dockerfile.test
    environment:
      # Добавляем пути, чтобы Python видел и пакет 'app', и модули внутри него (core, api)
      - PYTHONPATH=.:/app:/app/app

      # Настройки конфига
      - APP_CONFIG__DB__URL=postgresql+asyncpg://postgres:postgres@test-db:5432/postgres
      - APP_CONFIG__ACCESS_TOKEN__RESET_PASSWORD_TOKEN_SECRET=test_reset_secret_key_777
      - APP_CONFIG__ACCESS_TOKEN__VERIFICATION_TOKEN_SECRET=test_verify_secret_key_777

      # Дополнительные настройки для корректного вывода pytest
      - PYTHONUNBUFFERED=1
    depends_on:
      test-db:
        condition: service_healthy
    command: pytest tests

  test-db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 5
    ports:
      - "5433:5432" # Проброс порта, чтобы вы могли заглянуть в тестовую БД с хоста